[package]
name = "day14"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[[bin]]
name = "part1"

[[bin]]
name = "part2"

[dependencies]
color-eyre = "0.6.2"
ndarray = "0.15"
